// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Focus: typeof import('./../directives/focus.js')['default']
    IMyIconsArrow: typeof import('~icons/my-icons/arrow')['default']
    IMyIconsComponent: typeof import('~icons/my-icons/component')['default']
    IMyIconsEllipsis: typeof import('~icons/my-icons/ellipsis')['default']
    IMyIconsLayer: typeof import('~icons/my-icons/layer')['default']
    IMyIconsPreview: typeof import('~icons/my-icons/preview')['default']
    IMyIconsReceive: typeof import('~icons/my-icons/receive')['default']
    IMyIconsReload: typeof import('~icons/my-icons/reload')['default']
    IMyIconsTrigger: typeof import('~icons/my-icons/trigger')['default']
    InfoText: typeof import('./../components/InfoText.vue')['default']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCollapseTransition: typeof import('naive-ui')['NCollapseTransition']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NPopover: typeof import('naive-ui')['NPopover']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NTab: typeof import('naive-ui')['NTab']
    NTable: typeof import('naive-ui')['NTable']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTooltip: typeof import('naive-ui')['NTooltip']
  }
}

export { }
